# Generated by Django 3.1.7 on 2021-02-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_p',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('sq', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('bath', models.IntegerField(default=0)),
                ('bed', models.IntegerField(default=0)),
                ('address', models.TextField()),
                ('sale', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('status', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('sq', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('bath', models.IntegerField(default=0)),
                ('bed', models.IntegerField(default=0)),
                ('rent', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
            ],
        ),
    ]
